import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Router } from '@angular/router';

import { ButtonModule } from 'primeng/button';
import { DatePickerModule } from 'primeng/datepicker';
import { ToastModule } from 'primeng/toast';
import { MessageService } from 'primeng/api';

import jsPDF from 'jspdf';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ToastModule,
    ButtonModule,
    DatePickerModule
  ],
  providers: [MessageService],
  templateUrl: './reports.component.html',
  styleUrls: ['./reports.component.scss']
})
export class ReportsComponent implements OnInit {
  customerId = '';

 
  fromDate: Date = new Date();
  toDate: Date = new Date();

  loading = false;

  
  private readonly API = 'http://localhost:8080/reports';

  constructor(
    private route: ActivatedRoute,
    private http: HttpClient,
    private msg: MessageService,
     private router: Router
  ) {}

  ngOnInit(): void {
    this.customerId = this.route.snapshot.queryParamMap.get('customerId') ?? '';

   
    const today = new Date();
    const tomorrow = new Date(today);
    tomorrow.setDate(today.getDate() + 1);

    this.fromDate = today;
    this.toDate = tomorrow;
  }

  goBackToCustomers(): void {
  this.router.navigate(['/customers']);
}


  downloadPdf(): void {
    if (!this.customerId) {
      this.msg.add({ severity: 'warn', summary: 'Warning', detail: 'customerId is required' });
      return;
    }

    const from = this.toIsoDate(this.fromDate);
    const to = this.toIsoDate(this.toDate);

    const params = new HttpParams()
      .set('customerId', this.customerId)
      .set('from', from)
      .set('to', to);

    this.loading = true;

    
    this.http.get<any>(this.API, { params }).subscribe({
      next: (report) => {
        this.loading = false;
        this.buildPdfFromReport(report, from, to);
      },
      error: (err) => {
        this.loading = false;
        console.error(err);
        this.msg.add({ severity: 'error', summary: 'Error', detail: 'Report API error' });
      }
    });
  }

  private buildPdfFromReport(report: any, from: string, to: string): void {
  const doc = new jsPDF();


  const safe = this.sanitizeReport(report);

 
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 14;
  let y = 18;


  doc.setFontSize(18);
  doc.text('Customer Account Statement', marginX, y);
  y += 10;

  doc.setFontSize(11);
  doc.text(`Customer: ${safe.customerName ?? '-'}`, marginX, y); y += 6;
  doc.text(`Customer ID: ${safe.customerId ?? this.customerId}`, marginX, y); y += 6;
  doc.text(`Period: ${from} to ${to}`, marginX, y); y += 10;


  doc.setDrawColor(220);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 8;


  doc.setFontSize(12);
  doc.text('Summary', marginX, y);
  y += 7;

  doc.setFontSize(11);
  doc.text(`Total Credit: ${this.money(safe.totalCredit)}`, marginX, y); y += 6;
  doc.text(`Total Debit: ${this.money(safe.totalDebit)}`, marginX, y); y += 10;


  doc.setFontSize(12);
  doc.text('Accounts', marginX, y);
  y += 8;

  
  y = this.tableHeader(doc, y, ['Account #', 'Type', 'Balance']);

  const accounts = Array.isArray(safe.accounts) ? safe.accounts : [];
  if (accounts.length === 0) {
    doc.setFontSize(11);
    doc.text('No accounts found for this customer.', marginX, y);
    y += 8;
  } else {
    for (const a of accounts) {
      
      if (y > 275) {
        doc.addPage();
        y = 18;
        y = this.tableHeader(doc, y, ['Account #', 'Type', 'Balance']);
      }

      const row = [
        String(a.accountNumber ?? '-'),
        String(a.accountType ?? '-'),
        this.money(a.currentBalance ?? a.balance)
      ];

      y = this.tableRow(doc, y, row);
    }
  }


  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text('Generated by BANCO - Angular', marginX, 290);
  doc.setTextColor(0);

  doc.save(`report-${this.customerId}-${from}-${to}.pdf`);
}


  private toIsoDate(d: Date): string {
   
    const yyyy = d.getFullYear();
    const mm = String(d.getMonth() + 1).padStart(2, '0');
    const dd = String(d.getDate()).padStart(2, '0');
    return `${yyyy}-${mm}-${dd}`;
  }

  private sanitizeReport(report: any) {
  if (!report) return {};


  const copy: any = { ...report };

  if ('pdfBase64' in copy) delete copy.pdfBase64;


  if ('base64' in copy) delete copy.base64;

  return copy;
}

private money(value: any): string {
  const n = Number(value);
  if (Number.isNaN(n)) return '-';
  return n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}


private tableHeader(doc: jsPDF, y: number, headers: string[]): number {
  const x = 14;
  const col1 = x;
  const col2 = 90;
  const col3 = 150;

  doc.setFontSize(10);
  doc.setTextColor(60);

  doc.text(headers[0], col1, y);
  doc.text(headers[1], col2, y);
  doc.text(headers[2], col3, y);

  y += 4;
  doc.setDrawColor(200);
  doc.line(x, y, 196, y);
  y += 6;

  doc.setTextColor(0);
  return y;
}

private tableRow(doc: jsPDF, y: number, cols: string[]): number {
  const x = 14;
  const col1 = x;
  const col2 = 90;
  const col3 = 150;

  doc.setFontSize(10);

  doc.text(cols[0], col1, y);
  doc.text(cols[1], col2, y);
  doc.text(cols[2], col3, y);

  y += 6;
  doc.setDrawColor(235);
  doc.line(x, y, 196, y);
  y += 6;

  return y;
}

}
